//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGuild
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Founded { get; set; }
        public string LeaderName { get; set; }
        public int Members { get; set; }
        public int MembersOnline { get; set; }
        public string MotDescription { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> AllianceId { get; set; }
        public string AllianceName { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
