//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchievementCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AchievementCategory()
        {
            this.AchievementSubCategories = new HashSet<AchievementSubCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Achievements { get; set; }
        public int SubCategories { get; set; }
        public int TotalPoints { get; set; }
        public int EarnedPointes { get; set; }
        public int CharacterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchievementSubCategory> AchievementSubCategories { get; set; }
        public virtual Character Character { get; set; }
    }
}
