//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchievementSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AchievementSubCategory()
        {
            this.AchievementInfoes = new HashSet<AchievementInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Achievements { get; set; }
        public int TotalPoints { get; set; }
        public int EarnedPoints { get; set; }
        public int AchievementCategoryId { get; set; }
    
        public virtual AchievementCategory AchievementCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchievementInfo> AchievementInfoes { get; set; }
    }
}
