//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchievementCriteria
    {
        public int Id { get; set; }
        public bool Completed { get; set; }
        public bool Required { get; set; }
        public string Description { get; set; }
        public int AchievementInfoId { get; set; }
    
        public virtual AchievementInfo AchievementInfo { get; set; }
    }
}
