//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterQuest
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public string Name { get; set; }
        public System.DateTime Completed { get; set; }
        public int EventCode { get; set; }
        public int Level { get; set; }
        public int PreviousExperience { get; set; }
        public int CurrentExperience { get; set; }
        public int Rank { get; set; }
        public int PreviousPoints { get; set; }
        public int CurrentPoints { get; set; }
        public string Zone { get; set; }
    
        public virtual Character Character { get; set; }
    }
}
