//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterActivity
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public Nullable<int> AlliancePoints { get; set; }
        public Nullable<int> BankedCash { get; set; }
        public Nullable<int> BankedTelvarStones { get; set; }
        public Nullable<int> Cash { get; set; }
        public Nullable<int> ChampionPointsEarned { get; set; }
        public Nullable<int> GuildCount { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> MailCount { get; set; }
        public Nullable<int> MailMax { get; set; }
        public Nullable<int> MaxBagSize { get; set; }
        public Nullable<int> MaxBankSize { get; set; }
        public Nullable<int> NumberOfFriends { get; set; }
        public Nullable<long> SecondsPlayed { get; set; }
        public Nullable<int> UsedBagSlots { get; set; }
        public Nullable<int> UsedBankSlots { get; set; }
    
        public virtual Character Character { get; set; }
    }
}
