//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterInventory
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public long InstanceId { get; set; }
        public bool IsBound { get; set; }
        public bool IsConsumable { get; set; }
        public bool IsEquipable { get; set; }
        public bool IsJunk { get; set; }
        public bool IsUsable { get; set; }
        public string ItemStyle { get; set; }
        public int ItemType { get; set; }
        public int Location { get; set; }
        public string Link { get; set; }
        public int RequiredLevel { get; set; }
        public int RequiredVeteranRank { get; set; }
        public int StackSize { get; set; }
        public int StatValue { get; set; }
        public int TotalCount { get; set; }
        public int Trait { get; set; }
        public Nullable<bool> MeetsUsageRequirement { get; set; }
        public Nullable<int> SellPrice { get; set; }
        public string Icon { get; set; }
        public Nullable<int> ArmorType { get; set; }
        public Nullable<int> EquipType { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual ArmorTypeLookup ArmorTypeLookup { get; set; }
    }
}
