//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterStat
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public int AttackPower { get; set; }
        public int Block { get; set; }
        public int CriticalResistance { get; set; }
        public int CriticalStrike { get; set; }
        public int DamageResistCold { get; set; }
        public int DamageResistDisease { get; set; }
        public int DamageResistDrown { get; set; }
        public int DamageResistEarth { get; set; }
        public int DamageResistFire { get; set; }
        public int DamageResistGeneric { get; set; }
        public int DamageResistMagic { get; set; }
        public int DamageResistOblivion { get; set; }
        public int DamageResistPhysical { get; set; }
        public int DamageResistPoison { get; set; }
        public int DamageResistShock { get; set; }
        public int DamageResistStart { get; set; }
        public int Dodge { get; set; }
        public int HealingTaken { get; set; }
        public int HealthMax { get; set; }
        public int HealthRegenCombat { get; set; }
        public int HealthRegenIdle { get; set; }
        public int MagickaMax { get; set; }
        public int MagickaRegenCombat { get; set; }
        public int MagickaRegenIdle { get; set; }
        public int Miss { get; set; }
        public int MitigationX { get; set; }
        public int Parry { get; set; }
        public int PhysicalPenetration { get; set; }
        public int PhysicalResist { get; set; }
        public int Power { get; set; }
        public int SpellCritical { get; set; }
        public int SpellMitigation { get; set; }
        public int SpellPenetration { get; set; }
        public int SpellPower { get; set; }
        public int SpellResist { get; set; }
        public int StaminaMax { get; set; }
        public int StaminaRegenCombat { get; set; }
        public int StaminaRegenIdle { get; set; }
        public int WeaponPower { get; set; }
        public int ArmorRating { get; set; }
    
        public virtual Character Character { get; set; }
    }
}
