//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterDailyQuest
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public Nullable<System.DateTime> AlchemistCompleted { get; set; }
        public Nullable<int> AlchemistLevel { get; set; }
        public Nullable<System.DateTime> BlacksmithCompleted { get; set; }
        public Nullable<int> BlacksmithLevel { get; set; }
        public Nullable<System.DateTime> ClothierCompleted { get; set; }
        public Nullable<int> ClothierLevel { get; set; }
        public Nullable<System.DateTime> EnchanterCompleted { get; set; }
        public Nullable<int> EnchanterLevel { get; set; }
        public Nullable<System.DateTime> ProvisionerCompleted { get; set; }
        public Nullable<int> ProvisionerLevel { get; set; }
        public Nullable<System.DateTime> OrsiniumHeresyOfIgnoranceCompleted { get; set; }
        public Nullable<int> OrsiniumHeresyOfIgnoranceLevel { get; set; }
        public Nullable<System.DateTime> OrsiniumMadUrkazburCompleted { get; set; }
        public Nullable<int> OrsiniumMadUrkazburLevel { get; set; }
        public Nullable<System.DateTime> OrsiniumMeatForTheMassesCompleted { get; set; }
        public Nullable<int> OrsiniumMeatForTheMassesLevel { get; set; }
        public Nullable<System.DateTime> OrsiniumNaturesBountyCompleted { get; set; }
        public Nullable<int> OrsiniumNaturesBountyLevel { get; set; }
        public Nullable<System.DateTime> OrsiniumReekingOfFoulPlayCompleted { get; set; }
        public Nullable<int> OrsiniumReekingOfFoulPlayLevel { get; set; }
        public Nullable<System.DateTime> OrsiniumSnowAndSteamCompleted { get; set; }
        public Nullable<int> OrsiniumSnowAndSteamLevel { get; set; }
    
        public virtual Character Character { get; set; }
    }
}
