//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsoCharacter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EsoCharacter()
        {
            this.EsoEvents = new HashSet<EsoEvent>();
            this.EsoMounts = new HashSet<EsoMount>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int RaceId { get; set; }
        public int ClassId { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<long> TotalTimeMs { get; set; }
        public int AccountId { get; set; }
    
        public virtual EsoClass EsoClass { get; set; }
        public virtual EsoRace EsoRace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EsoEvent> EsoEvents { get; set; }
        public virtual EsoAccount EsoAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EsoMount> EsoMounts { get; set; }
    }
}
