//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsoEvent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime EventTime { get; set; }
        public int EventTypeId { get; set; }
        public string Event { get; set; }
        public int CharacterId { get; set; }
    
        public virtual EsoCharacter EsoCharacter { get; set; }
        public virtual EsoEventType EsoEventType { get; set; }
    }
}
