//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsoMount
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public int Speed { get; set; }
        public int Stamina { get; set; }
        public int Capacity { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<long> TimeUntilTraining { get; set; }
    
        public virtual EsoCharacter EsoCharacter { get; set; }
    }
}
