//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HemSoft.Eso.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsoEntities : DbContext
    {
        public EsoEntities()
            : base("name=EsoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EsoAccount> EsoAccounts { get; set; }
        public virtual DbSet<EsoCharacter> EsoCharacters { get; set; }
        public virtual DbSet<EsoClass> EsoClasses { get; set; }
        public virtual DbSet<EsoEvent> EsoEvents { get; set; }
        public virtual DbSet<EsoEventType> EsoEventTypes { get; set; }
        public virtual DbSet<EsoRace> EsoRaces { get; set; }
    }
}
