module App.Domain {
    export interface ICharacterActivity {
        Id: number,
        CharacterId: number,
        AlliancePoints: number,
        BankedCash: number,
        BankedTelvarStones: number,
        Cash: number,
        ChampionPointsEarned: number,
        GuildCount: number,
        LastLogin: Date,
        MailCount: number,
        MailMax: number,
        MaxBagSize: number,
        MaxBankSize: number,
        NumberOfFriends: number,
        SecondsPlayed: number,
        UsedBagSlots: number,
        UsedBankSlots: number,
        BlacksmithingSecondsMaximumLeft: number,
        BlacksmithingSecondsMaximumTotal: number,
        BlacksmithingSecondsMinimumLeft: number,
        BlacksmithingSecondsMinimumTotal: number,
        BlacksmithingSlotsFree: number,
        BlacksmithingSlotsMax: number,
        ClothingSecondsMaximumLeft: number,
        ClothingSecondsMaximumTotal: number,
        ClothingSecondsMinimumLeft: number,
        ClothingSecondsMinimumTotal: number,
        ClothingSlotsFree: number,
        ClothingSlotsMax: number,
        WoodworkingSecondsMaximumLeft: number,
        WoodworkingSecondsMaximumTotal: number,
        WoodworkingSecondsMinimumLeft: number,
        WoodworkingSecondsMinimumTotal: number,
        WoodworkingSlotsFree: number,
        WoodworkingSlotsMax: number,
        AvailableSkillPoints: number,
        Skyshards: number,
        MountCapacity: number,
        MountStamina: number,
        MountSpeed: number,
        SecondsUntilMountTraining: number,
        EnlightenedPool: number,
        Level: number,
        Zone: string,
        IsVeteran: boolean,
        VeteranRank: number,
        VP: number,
        VPMax: number,
        EffectiveLevel: number,
        AchievementPoints: number,
        Character: App.Domain.ICharacter,
    }

    export class CharacterActivity implements ICharacterActivity {

        constructor(public Id: number,
                    public CharacterId: number,
                    public AlliancePoints: number,
                    public BankedCash: number,
                    public BankedTelvarStones: number,
                    public Cash: number,
                    public ChampionPointsEarned: number,
                    public GuildCount: number,
                    public LastLogin: Date,
                    public MailCount: number,
                    public MailMax: number,
                    public MaxBagSize: number,
                    public MaxBankSize: number,
                    public NumberOfFriends: number,
                    public SecondsPlayed: number,
                    public UsedBagSlots: number,
                    public UsedBankSlots: number,
                    public BlacksmithingSecondsMaximumLeft: number,
                    public BlacksmithingSecondsMaximumTotal: number,
                    public BlacksmithingSecondsMinimumLeft: number,
                    public BlacksmithingSecondsMinimumTotal: number,
                    public BlacksmithingSlotsFree: number,
                    public BlacksmithingSlotsMax: number,
                    public ClothingSecondsMaximumLeft: number,
                    public ClothingSecondsMaximumTotal: number,
                    public ClothingSecondsMinimumLeft: number,
                    public ClothingSecondsMinimumTotal: number,
                    public ClothingSlotsFree: number,
                    public ClothingSlotsMax: number,
                    public WoodworkingSecondsMaximumLeft: number,
                    public WoodworkingSecondsMaximumTotal: number,
                    public WoodworkingSecondsMinimumLeft: number,
                    public WoodworkingSecondsMinimumTotal: number,
                    public WoodworkingSlotsFree: number,
                    public WoodworkingSlotsMax: number,
                    public AvailableSkillPoints: number,
                    public Skyshards: number,
                    public MountCapacity: number,
                    public MountStamina: number,
                    public MountSpeed: number,
                    public SecondsUntilMountTraining: number,
                    public EnlightenedPool: number,
                    public Level: number,
                    public Zone: string,
                    public IsVeteran: boolean,
                    public VeteranRank: number,
                    public VP: number,
                    public VPMax: number,
                    public EffectiveLevel: number,
                    public AchievementPoints: number,
                    public Character: App.Domain.ICharacter) {
        }
    }
}